variables:
  terraform_version: 1.3.7
  terraform_path: /usr/local/bin
  env: dev
  be_sa_name: saiqsrdev
  be_container_name: iqsr-dev

pool:
  vmImage: ubuntu-22.04

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    jobs:
      - job: terraform_plan
        displayName: Terraform Plan
        workspace:
          clean: all
        steps:
          - task: Bash@3
            displayName: install terraform
            inputs:
              targetType: filePath
              filePath: scripts/terraform_install.sh
              arguments: >
                -v $(terraform_version)
                -d $(terraform_path)
          - task: AzureCLI@2
            displayName: terraform init
            inputs:
              connectedServiceNameARM: sc-non-prod-iqsr-dev
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: scripts/terraform_plan.sh
              arguments: >
                -backend-config="storage_account_name=$(be_sa_name)"
                -backend-config="container_name=$(be_container_name)"
                -backend-config="key=$(env).tfstate"
                -backend-config="use_azuread_auth=true"
            env:
              TF_IN_AUTOMATION: true

  - stage: terraform_apply
    displayName: Terraform Apply
    jobs:
      - job: terraform_apply
        displayName: Terraform Apply
        workspace:
          clean: all
        steps:
          - script: echo apply
