variables:
  - group: terraform-base
  - group: devops-base
  - group: devops-non-prod
  - group: devops-dev

pool:
  vmImage: ubuntu-22.04

stages:
  - template: ./templates/plan.yml
    parameters:
      terraform_version: $(terraform_version)
      terraform_path:    $(terraform_path)
      tenancy:           $(tenancy)
      subscription_id:   $(subscription_id)
      client_id:         $(client_id)
      client_secret:     $(client_secret)
      sa:                $(sa)
      container:         $(container)
      environment:       $(environment)

  - template: ./templates/apply.yml
    parameters:
      terraform_version: $(terraform_version)
      terraform_path:    $(terraform_path)
      tenancy:           $(tenancy)
      subscription_id:   $(subscription_id)
      client_id:         $(client_id)
      client_secret:     $(client_secret)
      sa:                $(sa)
      container:         $(container)
      environment:       $(environment)
      azdo_release_env:  $(azdo_release_env)
