variables:
  terraform_version: 1.3.7
  terraform_path: /usr/local/bin

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    jobs:
      - job: terraform_plan
        displayName: Terraform Plan
        workspace:
          clean: all
        steps:
          - task: Bash@3
            displayName: install terraform
            inputs:
              targetType: filePath
              filePath: scripts/terraform_install.sh
              arguments: |
                -v $(terraform_version)
                -d $(terraform_path)
  - stage: terraform_apply
    displayName: Terraform Apply
    jobs:
      - job: terraform_apply
        displayName: Terraform Apply
        workspace:
          clean: all
        steps:
          - script: echo apply
